
package power.life.gym;

    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;


public class VentCliente extends javax.swing.JFrame {
 // cliente miCliente=new cliente();
 cliente tCliente;
   Integer index;
   
    public VentCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargaLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Modificar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        spinPeso = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        buteliminar = new javax.swing.JButton();
        txtCedula = new javax.swing.JFormattedTextField();
        txtNum = new javax.swing.JFormattedTextField();
        txtPago = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 435));
        setMinimumSize(new java.awt.Dimension(850, 435));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 435));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Completo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 107, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de pago:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peso:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtnombrePropertyChange(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, -1));
        getContentPane().add(spinPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 90, -1));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Telefono", "Fecha de pago", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 850, 200));

        buteliminar.setText("Eliminar");
        buteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buteliminarActionPerformed(evt);
            }
        });
        getContentPane().add(buteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        txtCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 300, -1));

        txtNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 300, -1));

        txtPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 300, -1));

        jButton1.setText("Retroceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/powerlife-gym.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtnombrePropertyChange
       
    }//GEN-LAST:event_txtnombrePropertyChange

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
     Agregar();
     CargaLista();
    }
    
    private void Agregar()
    {
         try
        {
            if(Validar())
            {
                if(tCliente==null){
                //nuevo
                cliente nuevoCliente =new cliente();
                nuevoCliente.nombre = txtnombre.getText();
                nuevoCliente.cedula = Integer.parseInt(txtCedula.getText()); 
                nuevoCliente.peso  =  (Integer)spinPeso.getValue();
                nuevoCliente.telefono = Integer.parseInt(txtNum.getText());
                nuevoCliente.fechapago = txtPago.getText();
                //
                cliente.Agregar(nuevoCliente);
            }
            else 
            {
                
                cliente.lista.get(index).nombre = txtnombre.getText();
                cliente.lista.get(index).cedula = Integer.parseInt(txtCedula.getText()); 
                cliente.lista.get(index).peso  =  (Integer)spinPeso.getValue();
                cliente.lista.get(index).telefono = Integer.parseInt(txtNum.getText());
                cliente.lista.get(index).fechapago = txtPago.getText();
                tCliente=null;
            }        
            LimpiaControles();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Digite información");
        }
    }//GEN-LAST:event_AgregarActionPerformed
      
    
    private void LimpiaControles(){
       
        txtnombre.setText("");
        txtCedula.setText("");
        spinPeso.setValue(0);
        txtNum.setText("");
        txtPago.setText("");
    }
    
    private boolean Validar(){
      
        if(txtnombre.getText()=="")
        {
            //mensaje de error
            return false;
        }
        return true;
    }   
       
public void CargaLista(){
DefaultTableModel modelo = (DefaultTableModel)tblCliente.getModel();
        modelo.getDataVector().removeAllElements();
        ((DefaultTableModel)tblCliente.getModel()).setNumRows(0);
        for(cliente item :      cliente.lista )     
        {
            Object[] obj = new Object[5];
            obj[0]= item.nombre;
            obj[1]= item.cedula;
            obj[2]= item.telefono;
            obj[3]= item.fechapago;
            obj[4]= item.peso;
            //
            modelo.addRow(obj);
        }
        //
        tblCliente.setModel(modelo);
}
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
    Modificar();
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void buteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buteliminarActionPerformed
        this.Eliminar();
    }//GEN-LAST:event_buteliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
   private void Eliminar(){
        try     
        {
            // toma el valor de la línea seleccionada
            index = tblCliente.getSelectedRow();
            // elimina la línea de la tabla
            DefaultTableModel model = (DefaultTableModel) tblCliente.getModel(); 
            if (index<0){
                JOptionPane.showMessageDialog(null,  "Debe seleccionar una fila de la tabla" );  
            }else {
                int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea Eliminar el registro? ");
                if(JOptionPane.OK_OPTION==confirmar) {
                    model.removeRow(index);
                    JOptionPane.showMessageDialog(null, "Registro Eliminado" );
                }
            }
            // elimina la línea de la lista.
            tCliente = (cliente)cliente.lista.get(index);           
            cliente.Eliminar(tCliente);
            CargaLista();
        }
        catch(Exception e)
        {
            JOptionPane.showInputDialog(null, e);
        }
    }
    private void Modificar(){
   
       index= tblCliente.getSelectedRow();
     tCliente=(cliente)cliente.lista.get(index);
        txtnombre.setText(tCliente.nombre);
        txtCedula.setValue(tCliente.cedula);
        spinPeso.setValue(tCliente.peso);
        txtNum.setValue(tCliente.telefono);
        txtPago.setText(tCliente.fechapago);
    }
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton buteliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spinPeso;
    private javax.swing.JTable tblCliente;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JFormattedTextField txtNum;
    private javax.swing.JFormattedTextField txtPago;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
